### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by ceeram** [FriendsOfCake/FriendsOfCake.github.io#2]
Replace logos with the new logo:

- github account
- irc.cakephp.nu
- twitter account
- anywhere else?

**Comment by jippi** [comment]
stalled

**Comment by chrisvogt** [comment]
For the record, I abducted the Friends Of Cake logo out of the website repository in hopes I could find it a new home all by itself.

Until that happens, you can find the logo assets at: [https://github.com/FriendsOfCake/FriendsOfCake.github.io/tree/0ebb203c58fcd86af5ca151702f41b5b05ffe227/images/logo](https://github.com/FriendsOfCake/FriendsOfCake.github.io/tree/0ebb203c58fcd86af5ca151702f41b5b05ffe227/images/logo).
