### ISSUE TITLE
Friends of Cake t-shirts!

### ISSUE THREAD

**Issue by bcrowe** [FriendsOfCake/FriendsOfCake.github.io#3]
Okay, kids... I have a buddy who does screen printing and I thought it might be cool to get some FoC t-shirts made.  That being said, they'll be free and I can get them shipped to your address.  Anyone interested?  If so, we should have a quick discussion on t-shirt color and the print.  Should the print be a small left-chest?  Big and center-chest? FoC website URL on the top of back? Etc...

If this generates any interest, I can take shipping addresses & t-shirt sizes to my email once t-shirt details have been ironed out / voted on.

**Comment by jippi** [comment]
Guess the answer is "no" ?

**Comment by davidyell** [comment]
Well you could have pinged @bcrowe to ask him? They might still be in the post! :wink:

**Comment by bcrowe** [comment]
:cry: The dream is dead!
