### ISSUE TITLE
Website Refresh

### ISSUE THREAD

**Issue by chrisvogt** [FriendsOfCake/FriendsOfCake.github.io#5]
Noticed this hasn't been updated in a while and felt it could use some updates. Here is a [website refresh](http://chrisvogt.github.io/FriendsOfCake.github.io). The repository is at [chrisvogt/FriendsOfCake.github.io](https://github.com/chrisvogt/FriendsOfCake.github.io).

![friendsofcake.com screenshot](http://i.imgur.com/VfzunlB.gif)

**Comment by jippi** [comment]
I like it - looks pretty good ! :)

**Comment by chrisvogt** [comment]
Thanks! I setup Travis and Jekyll, check out the source again. What would I need to do for this to be absorbed into FriendsOfCake and made live?

**Comment by josegonzalez** [comment]
Make a pull request.

**Comment by chrisvogt** [comment]
How's that @josegonzalez - and is it okay that I asked for Gitter to be setup, a `develop` branch to be created, etc?
